using System.Collections.Generic;
using System.IO;
using System.Text.RegularExpressions;

namespace tvn_cosine.languagedetector.util
{
    /// <summary> 
    /// This is Messages class generated by Eclipse automatically.
    /// Users don't use this class directly.
    /// </summary>
    public static class Messages
    {
        private static readonly IDictionary<string, string> properties; 

        static Messages()
        {
            if (!File.Exists("messages.properties"))
            {
                throw new FileNotFoundException("messages.properties does not exist.");
            }

            properties = new Dictionary<string, string>();

            using (StreamReader sr = new StreamReader("messages.properties"))
            { 
                string line = string.Empty;
                while (!sr.EndOfStream)
                {
                    line = sr.ReadLine();
                    string[] split = line.Split('=');
                    if (null != split
                     && split.Length == 2
                     && split[0].Length > 0
                     && split[1].Length > 0)
                    {
                        properties[split[0]] = Regex.Unescape(split[1]);
                    }
                }
            }
        }

        public static string getString(string key)
        { 
            if (!properties.ContainsKey(key))
            {
                throw new MissingPropertyException();
            }
            else
            {
                return properties[key];
            }
        }
    } 
}
